<?php
declare(strict_types=1);

/**
 * Default formulary seed: medication display name, therapeutic class (subcategory), shelf price (XAF), opening qty, reorder.
 *
 * @return list<array{name:string,subcategory:string,price:int,qty:int,reorder:int}>
 */
function hms_pharmacy_seed_medication_rows(): array
{
    return [
        ['name' => 'Paracetamol 500 mg tablets', 'subcategory' => 'Analgesics & antipyretics', 'price' => 100, 'qty' => 5000, 'reorder' => 800],
        ['name' => 'Paracetamol 1000 mg tablets', 'subcategory' => 'Analgesics & antipyretics', 'price' => 150, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Paracetamol syrup 120 mg/5 mL', 'subcategory' => 'Analgesics & antipyretics', 'price' => 800, 'qty' => 240, 'reorder' => 48],
        ['name' => 'Ibuprofen 400 mg tablets', 'subcategory' => 'Analgesics & antipyretics', 'price' => 120, 'qty' => 3000, 'reorder' => 500],
        ['name' => 'Ibuprofen 600 mg tablets', 'subcategory' => 'Analgesics & antipyretics', 'price' => 180, 'qty' => 1500, 'reorder' => 300],
        ['name' => 'Diclofenac 50 mg tablets', 'subcategory' => 'Analgesics & antipyretics', 'price' => 100, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Diclofenac 75 mg IM ampoule', 'subcategory' => 'Analgesics & antipyretics', 'price' => 600, 'qty' => 400, 'reorder' => 80],
        ['name' => 'Tramadol 50 mg capsules', 'subcategory' => 'Analgesics & antipyretics', 'price' => 250, 'qty' => 800, 'reorder' => 120],
        ['name' => 'Morphine sulfate 10 mg/mL ampoule', 'subcategory' => 'Analgesics & antipyretics', 'price' => 2500, 'qty' => 120, 'reorder' => 24],
        ['name' => 'Oral rehydration salts (ORS) sachets', 'subcategory' => 'Fluid & electrolytes', 'price' => 75, 'qty' => 5000, 'reorder' => 1000],
        ['name' => 'Ringers lactate 500 mL IV', 'subcategory' => 'Fluid & electrolytes', 'price' => 1800, 'qty' => 400, 'reorder' => 80],
        ['name' => 'Normal saline 0.9% 500 mL IV', 'subcategory' => 'Fluid & electrolytes', 'price' => 1500, 'qty' => 600, 'reorder' => 120],
        ['name' => 'Normal saline 0.9% 1000 mL IV', 'subcategory' => 'Fluid & electrolytes', 'price' => 2200, 'qty' => 400, 'reorder' => 80],
        ['name' => 'Dextrose 5% 500 mL IV', 'subcategory' => 'Fluid & electrolytes', 'price' => 1600, 'qty' => 350, 'reorder' => 70],
        ['name' => 'Artemether/Lumefantrine 20/120 mg tablets (blister)', 'subcategory' => 'Antimalarials', 'price' => 800, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Artesunate injection 60 mg', 'subcategory' => 'Antimalarials', 'price' => 4500, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Quinine dihydrochloride 300 mg/2 mL ampoule', 'subcategory' => 'Antimalarials', 'price' => 1200, 'qty' => 300, 'reorder' => 60],
        ['name' => 'Primaquine 7.5 mg tablets', 'subcategory' => 'Antimalarials', 'price' => 400, 'qty' => 600, 'reorder' => 120],
        ['name' => 'Sulfadoxine/Pyrimethamine tablets', 'subcategory' => 'Antimalarials', 'price' => 350, 'qty' => 800, 'reorder' => 160],
        ['name' => 'Amoxicillin 500 mg capsules', 'subcategory' => 'Antibiotics', 'price' => 150, 'qty' => 4000, 'reorder' => 800],
        ['name' => 'Amoxicillin/clavulanic acid 625 mg tablets', 'subcategory' => 'Antibiotics', 'price' => 450, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Azithromycin 500 mg tablets', 'subcategory' => 'Antibiotics', 'price' => 900, 'qty' => 1200, 'reorder' => 200],
        ['name' => 'Ciprofloxacin 500 mg tablets', 'subcategory' => 'Antibiotics', 'price' => 200, 'qty' => 2500, 'reorder' => 500],
        ['name' => 'Ceftriaxone 1 g powder for injection', 'subcategory' => 'Antibiotics', 'price' => 3500, 'qty' => 800, 'reorder' => 160],
        ['name' => 'Ceftriaxone 2 g powder for injection', 'subcategory' => 'Antibiotics', 'price' => 5500, 'qty' => 400, 'reorder' => 80],
        ['name' => 'Benzathine penicillin 2.4 MU vial', 'subcategory' => 'Antibiotics', 'price' => 1200, 'qty' => 300, 'reorder' => 60],
        ['name' => 'Metronidazole 500 mg tablets', 'subcategory' => 'Antibiotics', 'price' => 120, 'qty' => 3000, 'reorder' => 600],
        ['name' => 'Metronidazole 500 mg/100 mL IV infusion', 'subcategory' => 'Antibiotics', 'price' => 2200, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Doxycycline 100 mg capsules', 'subcategory' => 'Antibiotics', 'price' => 100, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Cotrimoxazole 960 mg tablets', 'subcategory' => 'Antibiotics', 'price' => 80, 'qty' => 5000, 'reorder' => 1000],
        ['name' => 'Fluconazole 150 mg capsule', 'subcategory' => 'Antifungals', 'price' => 800, 'qty' => 600, 'reorder' => 120],
        ['name' => 'Fluconazole 200 mg IV', 'subcategory' => 'Antifungals', 'price' => 4500, 'qty' => 80, 'reorder' => 16],
        ['name' => 'Nystatin oral suspension', 'subcategory' => 'Antifungals', 'price' => 1200, 'qty' => 120, 'reorder' => 24],
        ['name' => 'Omeprazole 20 mg capsules', 'subcategory' => 'Gastrointestinal', 'price' => 120, 'qty' => 4000, 'reorder' => 800],
        ['name' => 'Omeprazole 40 mg IV', 'subcategory' => 'Gastrointestinal', 'price' => 5500, 'qty' => 100, 'reorder' => 20],
        ['name' => 'Ranitidine 150 mg tablets', 'subcategory' => 'Gastrointestinal', 'price' => 90, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Hyoscine butylbromide 10 mg tablets', 'subcategory' => 'Gastrointestinal', 'price' => 150, 'qty' => 1500, 'reorder' => 300],
        ['name' => 'Oral rehydration zinc copack (ORS+Zn)', 'subcategory' => 'Gastrointestinal', 'price' => 120, 'qty' => 3000, 'reorder' => 600],
        ['name' => 'Lactulose syrup', 'subcategory' => 'Gastrointestinal', 'price' => 2500, 'qty' => 100, 'reorder' => 20],
        ['name' => 'Salbutamol inhaler 100 mcg/dose', 'subcategory' => 'Respiratory', 'price' => 3500, 'qty' => 400, 'reorder' => 80],
        ['name' => 'Beclometasone inhaler 200 mcg', 'subcategory' => 'Respiratory', 'price' => 5500, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Prednisolone 5 mg tablets', 'subcategory' => 'Respiratory', 'price' => 40, 'qty' => 5000, 'reorder' => 1000],
        ['name' => 'Amlodipine 5 mg tablets', 'subcategory' => 'Cardiovascular', 'price' => 80, 'qty' => 6000, 'reorder' => 1200],
        ['name' => 'Amlodipine 10 mg tablets', 'subcategory' => 'Cardiovascular', 'price' => 100, 'qty' => 4000, 'reorder' => 800],
        ['name' => 'Losartan 50 mg tablets', 'subcategory' => 'Cardiovascular', 'price' => 150, 'qty' => 3000, 'reorder' => 600],
        ['name' => 'Hydrochlorothiazide 25 mg tablets', 'subcategory' => 'Cardiovascular', 'price' => 50, 'qty' => 4000, 'reorder' => 800],
        ['name' => 'Furosemide 40 mg tablets', 'subcategory' => 'Cardiovascular', 'price' => 60, 'qty' => 3000, 'reorder' => 600],
        ['name' => 'Furosemide 20 mg/2 mL ampoule', 'subcategory' => 'Cardiovascular', 'price' => 400, 'qty' => 500, 'reorder' => 100],
        ['name' => 'Atorvastatin 20 mg tablets', 'subcategory' => 'Cardiovascular', 'price' => 200, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Glibenclamide 5 mg tablets', 'subcategory' => 'Endocrine & diabetes', 'price' => 40, 'qty' => 5000, 'reorder' => 1000],
        ['name' => 'Metformin 500 mg tablets', 'subcategory' => 'Endocrine & diabetes', 'price' => 60, 'qty' => 8000, 'reorder' => 1600],
        ['name' => 'Metformin 850 mg tablets', 'subcategory' => 'Endocrine & diabetes', 'price' => 80, 'qty' => 5000, 'reorder' => 1000],
        ['name' => 'Insulin NPH 100 IU/mL vial', 'subcategory' => 'Endocrine & diabetes', 'price' => 8500, 'qty' => 120, 'reorder' => 24],
        ['name' => 'Insulin regular 100 IU/mL vial', 'subcategory' => 'Endocrine & diabetes', 'price' => 8500, 'qty' => 100, 'reorder' => 20],
        ['name' => 'Levonorgestrel 1.5 mg tablet (EC)', 'subcategory' => 'Reproductive health', 'price' => 2500, 'qty' => 400, 'reorder' => 80],
        ['name' => 'Combined oral contraceptive (21+7)', 'subcategory' => 'Reproductive health', 'price' => 1200, 'qty' => 600, 'reorder' => 120],
        ['name' => 'Ferrous sulfate + folic acid tablets', 'subcategory' => 'Hematology & nutrition', 'price' => 100, 'qty' => 4000, 'reorder' => 800],
        ['name' => 'Vitamin B complex tablets', 'subcategory' => 'Hematology & nutrition', 'price' => 150, 'qty' => 3000, 'reorder' => 600],
        ['name' => 'Vitamin C 1000 mg effervescent', 'subcategory' => 'Hematology & nutrition', 'price' => 400, 'qty' => 1500, 'reorder' => 300],
        ['name' => 'Zinc sulfate 20 mg tablets', 'subcategory' => 'Hematology & nutrition', 'price' => 200, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Albendazole 400 mg tablets', 'subcategory' => 'Anthelmintics', 'price' => 300, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Mebendazole 100 mg tablets', 'subcategory' => 'Anthelmintics', 'price' => 150, 'qty' => 1500, 'reorder' => 300],
        ['name' => 'Praziquantel 600 mg tablets', 'subcategory' => 'Anthelmintics', 'price' => 800, 'qty' => 800, 'reorder' => 160],
        ['name' => 'Ceftazidime 1 g injection', 'subcategory' => 'Antibiotics', 'price' => 6500, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Meropenem 1 g powder for injection', 'subcategory' => 'Antibiotics', 'price' => 28000, 'qty' => 60, 'reorder' => 12],
        ['name' => 'Vancomycin 1 g powder for injection', 'subcategory' => 'Antibiotics', 'price' => 12000, 'qty' => 40, 'reorder' => 8],
        ['name' => 'Oxytocin 10 IU/mL ampoule', 'subcategory' => 'Obstetrics', 'price' => 800, 'qty' => 300, 'reorder' => 60],
        ['name' => 'Misoprostol 200 mcg tablets', 'subcategory' => 'Obstetrics', 'price' => 500, 'qty' => 500, 'reorder' => 100],
        ['name' => 'Magnesium sulfate 50% 10 mL ampoule', 'subcategory' => 'Obstetrics', 'price' => 600, 'qty' => 400, 'reorder' => 80],
        ['name' => 'Lidocaine 2% 20 mL vial', 'subcategory' => 'Anesthesia & procedures', 'price' => 1200, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Lidocaine/adrenaline dental cartridge', 'subcategory' => 'Anesthesia & procedures', 'price' => 350, 'qty' => 600, 'reorder' => 120],
        ['name' => 'Ketamine 50 mg/mL 10 mL vial', 'subcategory' => 'Anesthesia & procedures', 'price' => 4500, 'qty' => 80, 'reorder' => 16],
        ['name' => 'Haloperidol 5 mg/mL ampoule', 'subcategory' => 'Psychiatry', 'price' => 900, 'qty' => 150, 'reorder' => 30],
        ['name' => 'Diazepam 10 mg/2 mL ampoule', 'subcategory' => 'Psychiatry', 'price' => 500, 'qty' => 300, 'reorder' => 60],
        ['name' => 'Phenobarbital 200 mg/mL ampoule', 'subcategory' => 'Neurology', 'price' => 700, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Phenytoin 100 mg capsules', 'subcategory' => 'Neurology', 'price' => 120, 'qty' => 1000, 'reorder' => 200],
        ['name' => 'Carbamazepine 200 mg tablets', 'subcategory' => 'Neurology', 'price' => 100, 'qty' => 1200, 'reorder' => 240],
        ['name' => 'Allopurinol 100 mg tablets', 'subcategory' => 'Rheumatology & MSK', 'price' => 80, 'qty' => 800, 'reorder' => 160],
        ['name' => 'Prednisolone 25 mg tablets', 'subcategory' => 'Rheumatology & MSK', 'price' => 60, 'qty' => 1500, 'reorder' => 300],
        ['name' => 'Silver sulfadiazine cream 1%', 'subcategory' => 'Dermatology & topical', 'price' => 3500, 'qty' => 120, 'reorder' => 24],
        ['name' => 'Clotrimazole cream 1%', 'subcategory' => 'Dermatology & topical', 'price' => 800, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Miconazole cream 2%', 'subcategory' => 'Dermatology & topical', 'price' => 900, 'qty' => 180, 'reorder' => 36],
        ['name' => 'Permethrin 5% cream', 'subcategory' => 'Dermatology & topical', 'price' => 2500, 'qty' => 100, 'reorder' => 20],
        ['name' => 'Tetracycline eye ointment 1%', 'subcategory' => 'Ophthalmology', 'price' => 1200, 'qty' => 150, 'reorder' => 30],
        ['name' => 'Chloramphenicol eye drops 0.5%', 'subcategory' => 'Ophthalmology', 'price' => 900, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Artificial tears 10 mL', 'subcategory' => 'Ophthalmology', 'price' => 1500, 'qty' => 180, 'reorder' => 36],
        ['name' => 'Ciprofloxacin ear drops 0.3%', 'subcategory' => 'ENT', 'price' => 2200, 'qty' => 100, 'reorder' => 20],
        ['name' => 'Benzocaine/throat lozenges', 'subcategory' => 'ENT', 'price' => 400, 'qty' => 400, 'reorder' => 80],
        ['name' => 'Hydrocortisone cream 1%', 'subcategory' => 'Dermatology & topical', 'price' => 600, 'qty' => 250, 'reorder' => 50],
        ['name' => 'Calamine lotion 100 mL', 'subcategory' => 'Dermatology & topical', 'price' => 700, 'qty' => 150, 'reorder' => 30],
        ['name' => 'Acetylsalicylic acid 300 mg tablets', 'subcategory' => 'Analgesics & antipyretics', 'price' => 50, 'qty' => 4000, 'reorder' => 800],
        ['name' => 'Nitroglycerin 0.5 mg sublingual tablets', 'subcategory' => 'Cardiovascular', 'price' => 3500, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Digoxin 0.25 mg tablets', 'subcategory' => 'Cardiovascular', 'price' => 80, 'qty' => 600, 'reorder' => 120],
        ['name' => 'Spironolactone 25 mg tablets', 'subcategory' => 'Cardiovascular', 'price' => 100, 'qty' => 1500, 'reorder' => 300],
        ['name' => 'Enalapril 10 mg tablets', 'subcategory' => 'Cardiovascular', 'price' => 120, 'qty' => 2000, 'reorder' => 400],
        ['name' => 'Artesunate suppository 200 mg', 'subcategory' => 'Antimalarials', 'price' => 1800, 'qty' => 300, 'reorder' => 60],
        ['name' => 'Clindamycin 300 mg capsules', 'subcategory' => 'Antibiotics', 'price' => 400, 'qty' => 800, 'reorder' => 160],
        ['name' => 'Gentamicin 80 mg/2 mL ampoule', 'subcategory' => 'Antibiotics', 'price' => 350, 'qty' => 500, 'reorder' => 100],
        ['name' => 'Ceftazidime/avibactam 2.5 g vial', 'subcategory' => 'Antibiotics', 'price' => 45000, 'qty' => 24, 'reorder' => 6],
        ['name' => 'Ondansetron 4 mg tablets', 'subcategory' => 'Gastrointestinal', 'price' => 200, 'qty' => 1200, 'reorder' => 240],
        ['name' => 'Ondansetron 8 mg ODT', 'subcategory' => 'Gastrointestinal', 'price' => 350, 'qty' => 800, 'reorder' => 160],
        ['name' => 'Promethazine 25 mg tablets', 'subcategory' => 'Antiallergy', 'price' => 80, 'qty' => 1000, 'reorder' => 200],
        ['name' => 'Cetirizine 10 mg tablets', 'subcategory' => 'Antiallergy', 'price' => 100, 'qty' => 3000, 'reorder' => 600],
        ['name' => 'Chlorpheniramine 4 mg tablets', 'subcategory' => 'Antiallergy', 'price' => 40, 'qty' => 5000, 'reorder' => 1000],
        ['name' => 'Epinephrine 1 mg/mL ampoule', 'subcategory' => 'Emergency medicines', 'price' => 1500, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Atropine sulfate 1 mg/mL ampoule', 'subcategory' => 'Emergency medicines', 'price' => 400, 'qty' => 300, 'reorder' => 60],
        ['name' => 'Calcium gluconate 10% 10 mL ampoule', 'subcategory' => 'Emergency medicines', 'price' => 600, 'qty' => 200, 'reorder' => 40],
        ['name' => 'Sodium bicarbonate 8.4% 50 mL', 'subcategory' => 'Emergency medicines', 'price' => 1200, 'qty' => 120, 'reorder' => 24],
        ['name' => 'Naloxone 0.4 mg/mL ampoule', 'subcategory' => 'Emergency medicines', 'price' => 3500, 'qty' => 80, 'reorder' => 16],
    ];
}

/**
 * Capital equipment / reusable devices (priced as typical patient charge or rental fee).
 *
 * @return list<array{name:string,subcategory:string,price:int,qty:int,reorder:int}>
 */
function hms_pharmacy_seed_equipment_rows(): array
{
    return [
        ['name' => 'Digital BP monitor — automatic (adult cuff)', 'subcategory' => 'Diagnostic equipment', 'price' => 45000, 'qty' => 24, 'reorder' => 4],
        ['name' => 'Manual aneroid sphygmomanometer + stethoscope kit', 'subcategory' => 'Diagnostic equipment', 'price' => 35000, 'qty' => 18, 'reorder' => 3],
        ['name' => 'Dual-head stethoscope', 'subcategory' => 'Diagnostic equipment', 'price' => 12000, 'qty' => 30, 'reorder' => 6],
        ['name' => 'Pulse oximeter — fingertip', 'subcategory' => 'Diagnostic equipment', 'price' => 15000, 'qty' => 40, 'reorder' => 8],
        ['name' => 'Infrared ear/forehead thermometer', 'subcategory' => 'Diagnostic equipment', 'price' => 18000, 'qty' => 25, 'reorder' => 5],
        ['name' => 'Glucometer starter kit (meter + strips 50)', 'subcategory' => 'Diagnostic equipment', 'price' => 22000, 'qty' => 35, 'reorder' => 7],
        ['name' => 'Nebulizer compressor (home)', 'subcategory' => 'Respiratory equipment', 'price' => 55000, 'qty' => 15, 'reorder' => 3],
        ['name' => 'Wheelchair — standard folding', 'subcategory' => 'Mobility aids', 'price' => 95000, 'qty' => 10, 'reorder' => 2],
        ['name' => 'Crutches — axillary (pair)', 'subcategory' => 'Mobility aids', 'price' => 12000, 'qty' => 40, 'reorder' => 8],
        ['name' => 'Walker — folding', 'subcategory' => 'Mobility aids', 'price' => 28000, 'qty' => 12, 'reorder' => 2],
        ['name' => 'Examination couch cover — disposable roll', 'subcategory' => 'Clinical furniture consumables', 'price' => 15000, 'qty' => 20, 'reorder' => 4],
        ['name' => 'IV pole — stainless', 'subcategory' => 'Patient care equipment', 'price' => 45000, 'qty' => 14, 'reorder' => 2],
        ['name' => 'Bedpan — stainless', 'subcategory' => 'Patient care equipment', 'price' => 3500, 'qty' => 60, 'reorder' => 12],
        ['name' => 'Urinal — male', 'subcategory' => 'Patient care equipment', 'price' => 2500, 'qty' => 50, 'reorder' => 10],
        ['name' => 'Suction machine — portable', 'subcategory' => 'Emergency equipment', 'price' => 185000, 'qty' => 4, 'reorder' => 1],
        ['name' => 'Oxygen concentrator — 5 L/min', 'subcategory' => 'Respiratory equipment', 'price' => 420000, 'qty' => 3, 'reorder' => 1],
        ['name' => 'Otoscope/ophthalmoscope diagnostic set', 'subcategory' => 'Diagnostic equipment', 'price' => 95000, 'qty' => 6, 'reorder' => 1],
        ['name' => 'ECG electrodes — pack of 50', 'subcategory' => 'Diagnostic consumables', 'price' => 8000, 'qty' => 80, 'reorder' => 16],
    ];
}
